# Generated by Django 2.2.3 on 2019-07-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestcom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clients', to='Gestcom.Clients')),
            ],
        ),
    ]
